ci_config:
  raspi_controller_node: "raspi_controller_agent"
  raspi_device_node: "raspi_device_agent"
  workspace_base: "/mnt/tests"

  jfrog_config:
    jfrog_repo: "matter-Binaries"
    jfrog_server_id: "artifactory-oss"
    jfrog_url: "http://192.168.0.56:8082"
    jfrog_creds_id: "artifactory-jenkins-creds"

  clone_sdk_code_stage:
    node_to_clone_code: "node_to_clone_code"

    # Controller SDK configuration
    controller_sdk:
      branch: "v2.14+fall2025"
      tag: ""
      pr: ""
      sha: ""

    # Apps configuration per platform
    platforms:
      raspi:
        run: true
        controller_os: "raspi"
        controller_type: "python_controller"
        apps:
          - name: "all-clusters-app"
            branch: "v1.4-branch"
            tag: ""
            pr: ""
            sha: ""
          - name: "lighting-app"
            branch: "v1.5-branch"
            tag: ""
            pr: ""
            sha: ""

    matter_qa_repo_git_config:
      repoUrl: "git@github.com:CHIP-Specifications/matter-qa.git"
      branch: "main"
      sha: ""
      tag: ""
      pr: ""

  raspi_pipeline:
    stages:
      build_firmware:
        fresh_install: true
        chip_cert_bins: ca9d1118e097fe947b2aec1ba84f265d6cf2447e
        docker_image: "chip_image"
        node: "local_mac_node"
      run_tests:
        enabled: true
