# =============================================================================
# ci_config.yaml - CI/CD Pipeline Configuration for Jenkins Workflow
# =============================================================================
# This configuration file serves as an input to the Jenkins CI/CD pipeline.
# It defines environment settings, source control parameters, application
# under test, and pipeline execution stages for various platforms (e.g., RPi, Nordic).
#
# Usage:
# - This file is passed as a Jenkins pipeline input to control what stages are
#   executed, which repositories and branches to use, and which nodes to target.
# - Update repository URLs, branches, tags, or specific SHAs as needed.
# - Toggle stages or entire pipelines using the `enabled` and `run` flags.

# ci_config:
#   raspi_controller_node:       Dedicated Raspberry's Pi nodes for controller operations
#   raspi_device_node:           Dedicated Raspberry's Pi nodes for device operations
ci_config:
  raspi_controller_node: "raspi_controller_agent"
  raspi_device_node: "raspi_device_agent"
  workspace_base: "/mnt/tests"

  jfrog_config:
    jfrog_repo: "matter-Binaries"
    jfrog_server_id: "artifactory-oss"
    jfrog_url: "http://192.168.0.56:8082"
    jfrog_creds_id: "artifactory-jenkins-creds"

  clone_sdk_code_stage:
    node_to_clone_code: "node_to_clone_code"

    # ARTIFACT STRUCTURE platform
    platforms:
      raspi:
        run: true
        controller_os: "raspi"
        controller_type: "python_controller"
        app_to_test: "all-clusters-app"
      nordic:
        run: true
        controller_os: "linux"
        controller_type: "python_controller"
        app_to_test: "all-clusters-app"
      silabs:
        run: true
        controller_os: "linux"
        controller_type: "python_controller"
        app_to_test: "all-clusters-app"
      esp32:
        run: false
        variants:
          esp32c3:
            run: false
            controller_os: "linux"
            controller_type: "python_controller"
            app_to_test: "all-clusters-app"
          esp32c6:
            run: false
            controller_os: "linux"
            controller_type: "python_controller"
            app_to_test: "all-clusters-app"
          esp32h2:
            run: false
            controller_os: "linux"
            controller_type: "python_controller"
            app_to_test: "all-clusters-app"

    controller_sdk_config:
      controller_repo: "connectedhomeip"
      repoUrl: "git@github.com:project-chip/connectedhomeip.git"
      branch: "v2.14+fall2025"
      sha: ""
      tag: ""
      pr: ""
    apps_sdk_config:
      repoUrl: "git@github.com:project-chip/connectedhomeip.git"
      branch: "v1.4-branch"
      sha: ""
      tag: ""
      pr: ""
    matter_qa_repo_git_config:
      repoUrl: "git@github.com:CHIP-Specifications/matter-qa.git"
      branch: "main"
      sha: ""
      tag: ""
      pr: ""

  # raspi_pipeline:
  raspi_pipeline:
    stages:
      build_firmware:
        fresh_install: true
        chip_cert_bins: ca9d1118e097fe947b2aec1ba84f265d6cf2447e
        docker_image: "chip_image"
        node: "local_mac_node"
      run_tests:
        enabled: true
