@Library('jenkins-ci-lib') _
import com.matterci.pipelineLib.ConfigLoader

/**
 * Main Jenkins pipeline for Matter QA testing across platforms (Raspi, Nordic, Silabs).
 * Handles configuration loading, parallel test execution, and artifact management.
 */

node {

    // Define the tool globally for the workspace
    def jfHome = tool 'jfrog-cli'
    env.PATH = "${jfHome}:${env.PATH}"
    sh 'jf -v'
    sh 'jf c show'
    sh 'jf rt ping'

    // 2. Use matching names for the variables
    // withCredentials([usernamePassword(credentialsId: 'artifactory-jenkins-creds', 
    //                                  passwordVariable: 'JF_PASSWORD', 
    //                                  usernameVariable: 'JF_USER')]) {
        
    // // Add --insecure-tls=true to the config command
    //     sh "jf c add artifactory-oss --url=http://192.168.0.56:8082 --user=$JF_USER --password=$JF_PASSWORD --insecure-tls=true --overwrite --interactive=false"
    //     sh "jf c use artifactory-oss"
    // }

    properties([
        parameters([
            string(name: 'ci_config_file', defaultValue: '~/jenkins-config/ci_config.yaml', description: 'Path to CI configuration YAML file'),
            string(name: 'test_run_config_file', defaultValue: '~/jenkins-config/test_run_config.yaml', description: 'Path to Test Run configuration YAML file'),
        ])
    ])
    // Override config file paths if provided in environmental variables
    script {
        env.ci_config_file = env.INJECTED_CI_CONFIG_FILE ?: params.ci_config_file
        env.test_run_config_file = env.INJECTED_TEST_RUN_CONFIG_FILE ?: params.test_run_config_file

        echo "Using CI config file path: ${env.ci_config_file}"
        echo "Using Test run config file path: ${env.test_run_config_file}"
    }

    // Load configuration using two config files
    def testConfigs = ConfigLoader.loadMergedConfig(this)

    // override YAML settings with user provided settings in the UI, bit crazy here
    // The user provided value can be overwritten with Injected env params here
    //def numberOfIterations = env.INJECTED_NUMBER_OF_ITERATIONS ?: params.number_of_iterations
    //testConfigs.general_configs.number_of_iterations = numberOfIterations.toInteger()

    def testCasesList = [] //ConfigLoader.getTestCaseList(testConfigs)
    echo "Loaded test cases: ${testCasesList}"

    //assign these before starting the test so that python runner has this info to store in DB.

    if (testConfigs.ci_config?.clone_sdk_code_stage?.enabled){
        testConfigs = cloneRepo(testConfigs)
    }
    else{
        echo "do nothing, need to fix this to load the binaries from artifactory server"
    }
    //store the configs in the env after updating with SDK SHA
    env.testConfigs = testConfigs
    echo "Test Parameters: ${testConfigs}"

    if (testConfigs.ci_config?.raspi_pipeline?.run)
        raspiPipeline(testConfigs, testCasesList)

}
