@Library('backwardCompatibility-ci-lib') _
import com.matterci.pipelineLib.ConfigLoader
import com.matterci.pipelineLib.commonPipelineLib

node {
    properties([
        parameters([
            string(name: 'ci_config_file',defaultValue: '~/jenkins-config/ci_config.yaml',description: 'Path to CI configuration YAML file'),
            string(name: 'test_run_config_file',defaultValue: '~/jenkins-config/test_run_config.yaml',description: 'Path to Test Run configuration YAML file'),
        ])
    ])

    script {
        env.ci_config_file = env.INJECTED_CI_CONFIG_FILE ?: params.ci_config_file
        env.test_run_config_file = env.INJECTED_TEST_RUN_CONFIG_FILE ?: params.test_run_config_file
        echo "Using CI config file path: ${env.ci_config_file}"
        echo "Using Test run config file path: ${env.test_run_config_file}"
    }

    def testConfigs = ConfigLoader.loadMergedConfig(this)
    def testCasesList = []
    echo "Loaded test cases: ${testCasesList}"
    commonPipelineLib.setupJfrog(this, testConfigs)
    testConfigs = commonPipelineLib.resolveBranchSHA(this, testConfigs)
    commonPipelineLib.validateSdkConfig(this, testConfigs)
    commonPipelineLib.overrideDockerImageForRelease(this, testConfigs)

    //Artifact Decision Engine

    def decision =commonPipelineLib.resolveArtifactAndBuildDecision(this, testConfigs)
    testConfigs.ci_config.artifactDecision = decision

    //Clone Decision Logic
    def controllerBranch = testConfigs.ci_config.clone_sdk_code_stage.controller_sdk.branch
    def controllerRepo = commonPipelineLib.resolveRepo(controllerBranch)

    //Detect controller clone requirement
    def controllerCloneRequired = decision.platforms.values().any { it.controllerMissing }

    //Detect connectedhomeip apps clone requirement
    def connectedhomeipAppsCloneRequired = decision.platforms.values().any { platform ->
        platform.apps.any { app ->
            app.missing &&
            app.repo == "connectedhomeip"
        }
    }

    //Detect certification-tool apps build requirement
    def certificationToolAppsMissing = decision.platforms.values().any { platform ->
        platform.apps.any { app ->
            app.missing &&
            app.repo == "certification-tool"
        }
    }

    //Execute SDK clone ONLY when required
    if ((controllerCloneRequired && controllerRepo == "connectedhomeip") || connectedhomeipAppsCloneRequired ) {
        echo "Cloning connectedhomeip SDK (required)"
        testConfigs = cloneRepo(testConfigs, decision)
    }

    if (certificationToolAppsMissing) {
        echo "Certification-tool accessories will be built later"
    }
    env.testConfigs = testConfigs
    //Platform Execution
    def platforms = testConfigs.ci_config.clone_sdk_code_stage.platforms

    platforms.each { platformName, cfg ->
        if (!cfg.run)
            return

        if (platformName == "raspi") {
            raspiPipeline(testConfigs, testCasesList)
        }
    }
}